In [1]:
import numpy as np
X = np.random.randn(10000, 200).astype('f')
X

array([[ 1.51336062, -1.72516632, -0.16158368, ..., -2.23360467,
        -0.98010987,  0.59081805],
       [-0.55599308,  0.81194377, -0.04211446, ...,  0.87449133,
        -0.52738947,  0.83510816],
       [-0.27010837,  1.83134162, -0.19455622, ...,  0.36813027,
         1.17087388,  0.65210319],
       ..., 
       [-0.5540666 , -0.15921022, -0.98037314, ..., -0.36791426,
         1.15787017,  1.86880767],
       [-0.09052645, -1.26409817,  0.15429991, ...,  0.22700159,
        -1.21110928,  0.59996492],
       [ 0.91281378,  1.31797945, -0.03025524, ..., -0.34741056,
        -1.59094894, -0.38270435]], dtype=float32)

In [2]:
X.nbytes

8000000

In [7]:
from sys import getsizeof
list  = X[0].tobytes()
print(getsizeof(list))
#print(list)
decode = np.fromstring(list, dtype='<f4')
#print(X[0])
#print(decode)
print(X[0] == decode)
len(list)
for r in range (len(list)):
    print(list[r])
print(list)
print(list[0])


833
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  Tru

In [18]:
import pickle
list = pickle.dumps(X[0])

print(len(list))
decode = pickle.loads(list)
print(X[0] == decode)
print(list)

958
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  Tru

In [22]:
list = X[0].tolist()
print(len(list))
print(list)
decode = np.array(list, dtype=np.float32)
print(X[0] == decode)
print(list)

200
[1.513360619544983, -1.7251663208007812, -0.16158367693424225, 0.913257360458374, 0.8494617938995361, 1.0973505973815918, 0.8434866666793823, 1.35525381565094, 0.291909784078598, -0.07000643759965897, -0.48109927773475647, 0.5484466552734375, 0.10630122572183609, -1.7821117639541626, 0.5169783234596252, 1.412893295288086, -0.4281141459941864, -0.3217312693595886, -0.8688220977783203, 1.4248217344284058, 1.0915191173553467, 0.29060158133506775, -0.9629327058792114, -2.1362972259521484, -1.0850136280059814, -0.03327715024352074, 1.2832930088043213, 0.22600562870502472, 1.7043535709381104, -0.25155937671661377, 0.41003844141960144, -0.05162135884165764, 0.14462289214134216, -0.8321897387504578, -0.5678533315658569, 0.1898680180311203, -1.3542519807815552, 0.6280324459075928, 0.12568438053131104, 0.8200896978378296, 0.8695416450500488, 0.4814178943634033, -0.20519179105758667, -0.6337082386016846, 0.6131079792976379, -0.8173689842224121, 1.1942508220672607, -0.7441491484642029, -0.8977

In [39]:
import sqlite3 as sql
import time

con = sql.connect('test.db',isolation_level=None)
cur = con.cursor()
cur.execute("DROP TABLE IF EXISTS numpytest")
con.commit()
cur.execute("CREATE TABLE numpytest (id INTEGER PRIMARY KEY, array BLOB)")
con.commit()

In [40]:
t0 = time.time()
cur.execute("BEGIN")
for r in range(0, X.shape[0]):
    cur.execute("INSERT INTO numpytest VALUES (?,?)", (None, pickle.dumps(X[r])) )
cur.execute("END")
con.commit()
t1 = time.time()
print("% segundos decorridos...", (t1-t0))
print("% segundo por registro.", (t1-t0)/X.shape[0])
X

% segundos decorridos... 0.9370012283325195
% segundo por registro. 9.370012283325195e-05


array([[ 1.51336062, -1.72516632, -0.16158368, ..., -2.23360467,
        -0.98010987,  0.59081805],
       [-0.55599308,  0.81194377, -0.04211446, ...,  0.87449133,
        -0.52738947,  0.83510816],
       [-0.27010837,  1.83134162, -0.19455622, ...,  0.36813027,
         1.17087388,  0.65210319],
       ..., 
       [-0.5540666 , -0.15921022, -0.98037314, ..., -0.36791426,
         1.15787017,  1.86880767],
       [-0.09052645, -1.26409817,  0.15429991, ...,  0.22700159,
        -1.21110928,  0.59996492],
       [ 0.91281378,  1.31797945, -0.03025524, ..., -0.34741056,
        -1.59094894, -0.38270435]], dtype=float32)

In [41]:
t0 = time.time()
cur.execute("SELECT array FROM numpytest")
data = cur.fetchall()
t1 = time.time()
X2 = np.empty((len(data), 200))
for r in range(0, len(data)):
    Y = np.array(pickle.loads(data[r][0]), dtype=np.float32)
    X2 [r] = Y
t2 = time.time()
print("% segundos decorridos para o FETCH", (t1-t0))
print("% segundos para conversão e montagem do array.", (t2-t1))
X2

% segundos decorridos para o FETCH 0.023945093154907227
% segundos para conversão e montagem do array. 0.07895588874816895


array([[ 1.51336062, -1.72516632, -0.16158368, ..., -2.23360467,
        -0.98010987,  0.59081805],
       [-0.55599308,  0.81194377, -0.04211446, ...,  0.87449133,
        -0.52738947,  0.83510816],
       [-0.27010837,  1.83134162, -0.19455622, ...,  0.36813027,
         1.17087388,  0.65210319],
       ..., 
       [-0.5540666 , -0.15921022, -0.98037314, ..., -0.36791426,
         1.15787017,  1.86880767],
       [-0.09052645, -1.26409817,  0.15429991, ...,  0.22700159,
        -1.21110928,  0.59996492],
       [ 0.91281378,  1.31797945, -0.03025524, ..., -0.34741056,
        -1.59094894, -0.38270435]])

In [42]:
delta = X - X2

In [43]:
print(delta.sum())

0.0
